version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app
    env_file:
      - ./backend/.env
    # El backend ahora depende de AMBAS bases de datos
    depends_on:
      - postgres
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: bun run dev -- --host

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=danro
      - POSTGRES_PASSWORD=danrodev
      - POSTGRES_DB=agente_db
    restart: always

  # --- NUEVO SERVICIO DE REDIS ---
  redis:
    image: redis:7-alpine
    restart: always
    #ports:
    # Descomenta si necesitas conectarte desde tu PC con un cliente de Redis
    # - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: # --- NUEVO VOLUMEN PARA PERSISTENCIA DE REDIS ---
